apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-test-project-hpa
  namespace: my-test-project-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-test-project-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
